# Generated by Django 5.2.14 on 2026-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='interest',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Donate', 'Donate'), ('Partner', 'Partner'), ('General Inquiry', 'General Inquiry')], default='General Inquiry', max_length=50),
        ),
    ]
